import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#006948',
        'on-primary': '#ffffff',
        'primary-container': '#00855d',
        'on-primary-container': '#f5fff7',
        'primary-fixed': '#85f8c4',
        'primary-fixed-dim': '#68dba9',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#005137',
        'inverse-primary': '#68dba9',
        secondary: '#006398',
        'on-secondary': '#ffffff',
        'secondary-container': '#5bb8fe',
        'on-secondary-container': '#00476e',
        'secondary-fixed': '#cce5ff',
        'secondary-fixed-dim': '#93ccff',
        'on-secondary-fixed': '#001d31',
        'on-secondary-fixed-variant': '#004b73',
        tertiary: '#825100',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a36700',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#faf8ff',
        'on-background': '#131b2e',
        surface: '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#3d4a42',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: '#6d7a72',
        'outline-variant': '#bccac0',
        'surface-tint': '#006c4a',
        'surface-variant': '#dae2fd',
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'metric-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'metric-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        code: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        display: ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'metric-xl': ['32px', { lineHeight: '38px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'metric-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        code: ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        gutter: '1.5rem',
        'gutter-sm': '1rem',
        margin: '2rem',
        'margin-sm': '1rem',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 3px 0 rgba(15,23,42,0.05), 0 1px 2px -1px rgba(15,23,42,0.05)',
        md: '0 4px 6px -1px rgba(15,23,42,0.07), 0 2px 4px -2px rgba(15,23,42,0.05)',
        lg: '0 20px 25px -5px rgba(15,23,42,0.08), 0 8px 10px -6px rgba(15,23,42,0.04)',
        nav: '0 1px 8px rgba(0,0,0,0.04)',
      },
    },
  },
  plugins: [],
}

export default config
